Add support for nios2/bfin embedded targets and update help output to include information about softfloat toolchains. Package-Manager: portage-2.1_pre3-r1

diff --git a/sys-devel/crossdev/files/crossdev b/sys-devel/crossdev/files/crossdev
--- a/sys-devel/crossdev/files/crossdev
+++ b/sys-devel/crossdev/files/crossdev
@@ -1,7 +1,7 @@
 #!/bin/bash
-# Copyright 1999-2005 Gentoo Foundation
+# Copyright 1999-2006 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/sys-devel/crossdev/files/crossdev,v 1.41 2005/11/18 04:02:33 vapier Exp $
+# $Header: /var/cvsroot/gentoo-x86/sys-devel/crossdev/files/crossdev,v 1.42 2006/01/02 21:21:40 vapier Exp $
 
 cd /
 
@@ -22,6 +22,8 @@ die() {
 }
 
 usage() {
+	local exit_status=${1:-0}
+	shift
 cat << EOF
 Usage: ${HILITE}crossdev${NORMAL} ${GOOD}[options]${NORMAL} ${BRACKET}--target TARGET${NORMAL}
 
@@ -46,7 +48,8 @@ Extra Fun (must be run after above stages):
 ${BRACKET}Target (-t)${NORMAL}:   takes the form: ${BRACKET}ARCH-VENDOR-OS-LIBC${NORMAL}
     Run 'crossdev -t help' for examples
 EOF
-	exit ${1:-0}
+	[[ -n $* ]] && echo && eerror "Error: $*"
+	exit ${exit_status}
 }
 STAGE_BINUTILS=0
 STAGE_C_ONLY=1
@@ -63,8 +66,9 @@ parse_target() {
 	if [[ ${CTARGET/-} == ${CTARGET} || -z ${CPOST} ]] ; then
 		case ${CPRE} in
 			x86|i?86*|amd64|x86_64*) CPOST="pc-linux-gnu";;
-			s390*) CPOST="ibm-linux-gnu";;
-			*) CPOST="unknown-linux-gnu";;
+			s390*)                   CPOST="ibm-linux-gnu";;
+			bfin*|nios2*)            CPOST="elf";;
+			*)                       CPOST="unknown-linux-gnu";;
 		esac
 	fi
 
@@ -95,15 +99,27 @@ parse_target() {
 
 		#####################
 		### other targets ###
-		avr*) TARCH=${HARCH}; CPOST="";
+		avr*) TARCH=${HARCH}; CPOST="1";
 		      KPKG="[none]"; STAGE=${STAGE_LIBC};
 		      LCAT="dev-embedded"; LPKG="avr-libc";
 		      GVER="3.4.4-r1"; BVER="2.16.1";
 		      GUSE="-fortran -gtk -gcj -objc";;
 
+		bfin*)
+		      TARCH=${HARCH};
+		      BPKG="binutils-bfin";
+		      GPKG="gcc-bfin";
+		      STAGE=${STAGE_C_ONLY};;
+
 		msp430)
 		      TARCH=${HARCH}; CPOST="";
 		      STAGE=${STAGE_BINUTILS};;
+
+		nios2*)
+		      TARCH=${HARCH};
+		      BPKG="binutils-nios2";
+		      GPKG="gcc-nios2";
+		      STAGE=${STAGE_C_ONLY};;
 
 		ps2*) einfo "The ps2 target is really an alias for the ee/iop/dvp targets"
 		      ${CROSSDEV} -t ee  || exit 1
@@ -128,33 +144,34 @@ parse_target() {
 		help)
 			cat <<-EOF
 			Supported Architectures:
-			   alpha
-			   arm / armeb
-			   hppa (parisc)
-			   ia64
-			   i386 / i486 / i586 / i686 (x86)
-			   m68k
-			   mips / mipsel / mips64 / mips64el
-			   powerpc (ppc) / powerpc64 (ppc64)
-			   sparc / sparc64
-			   s390 / s390x
-			   sh / sh[1-5] / sh64
-			   x86_64 (amd64)
+			   - alpha                                     - arm / armeb
+			   - hppa (parisc)                             - ia64
+			   - i386 / i486 / i586 / i686 (x86)           - m68k
+			   - mips / mipsel / mips64 / mips64el
+			   - powerpc (ppc) / powerpc64 (ppc64)
+			   - sparc / sparc64                           - s390 / s390x
+			   - sh / sh[1-5] / sh64                       - x86_64 (amd64)
 			Supported C Libraries:
-			   gnu (glibc)
-			   klibc       [prob wont work]
-			   uclibc      [not all arches are ported]
+			   - gnu (glibc)
+			   - klibc       [prob wont work]
+			   - uclibc      [not all arches are ported]
 			Special Targets:
-			   avr
-			   msp430
-			   ee / iop / dvp (ps2) [Playstation 2 targets]
+			   - avr      http://www.nongnu.org/avr-libc/
+			   - bfin     http://blackfin.uclinux.org/
+			   - msp430   http://mspgcc.sourceforge.net/
+			   - nios2    http://www.altera.com/products/ip/processors/nios2/ni2-index.html
+			   - ee / iop / dvp (ps2) [Playstation 2 targets]
+			Softfloat toolchains:
+			   Set the 'vendor' field to 'softfloat'
+			   e.g. armeb-softfloat-linux-uclibc
+			        powerpc-softfloat-linux-gnu
 			EOF
 			exit 0
 			;;
 
 		#######################
 		### unknown targets ###
-		*) usage 1;;
+		*) usage 1 "Unknown target '$1'; bug vapier@gentoo.org to add it" ;;
 	esac
 
 	CTARGET=${CPRE}
