Fix 96577: compilation without arts installed. Package-Manager: portage-2.0.51.22-r1

diff --git a/media-sound/k3guitune/files/k3guitune-0.4.1-configure.patch b/media-sound/k3guitune/files/k3guitune-0.4.1-configure.patch
--- a/media-sound/k3guitune/files/k3guitune-0.4.1-configure.patch
+++ b/media-sound/k3guitune/files/k3guitune-0.4.1-configure.patch
@@ -1,7 +1,6 @@
-diff -Nur k3guitune-0.4.1.orig/configure k3guitune-0.4.1/configure
---- k3guitune-0.4.1.orig/configure	2004-08-18 15:10:29.000000000 +0200
-+++ k3guitune-0.4.1/configure	2005-04-03 18:41:51.000000000 +0200
-@@ -14073,71 +14073,6 @@
+--- configure.orig	2005-06-30 20:27:58.000000000 +0300
++++ configure	2005-06-30 20:28:25.000000000 +0300
+@@ -14073,138 +14073,6 @@
     fi
  
  
@@ -70,6 +69,95 @@ diff -Nur k3guitune-0.4.1.orig/configure k3guitune-0.4.1/configure
 -
 -   fi
 -
+-
+-   echo "$as_me:$LINENO: checking for artsc-config" >&5
+-echo $ECHO_N "checking for artsc-config... $ECHO_C" >&6
+-   if test -n "$ARTSCCONFIG"; then
+-        kde_cv_path="$ARTSCCONFIG";
+-   else
+-        kde_cache=`echo artsc-config | sed 'y%./+-%__p_%'`
+-
+-        if eval "test \"\${kde_cv_path_$kde_cache+set}\" = set"; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-
+-        kde_cv_path="NONE"
+-	dirs="$kde_default_bindirs"
+-	kde_save_IFS=$IFS
+-	IFS=':'
+-	for dir in $PATH; do
+-	  dirs="$dirs $dir"
+-        done
+-	IFS=$kde_save_IFS
+-
+-        for dir in $dirs; do
+-	  if test -x "$dir/artsc-config"; then
+-	    if test -n ""
+-	    then
+-              evalstr="$dir/artsc-config  2>&1 "
+-	      if eval $evalstr; then
+-                kde_cv_path="$dir/artsc-config"
+-                break
+-	      fi
+-            else
+-		kde_cv_path="$dir/artsc-config"
+-                break
+-	    fi
+-          fi
+-        done
+-
+-        eval "kde_cv_path_$kde_cache=$kde_cv_path"
+-
+-
+-fi
+-
+-
+-      eval "kde_cv_path=\"`echo '$kde_cv_path_'$kde_cache`\""
+-
+-   fi
+-
+-   if test -z "$kde_cv_path" || test "$kde_cv_path" = NONE; then
+-      echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6
+-
+-    { { echo "$as_me:$LINENO: error: The important program artsc-config was not found!
+-Please check whether you installed KDE correctly.
+-" >&5
+-echo "$as_me: error: The important program artsc-config was not found!
+-Please check whether you installed KDE correctly.
+-" >&2;}
+-   { (exit 1); exit 1; }; }
+-
+-   else
+-      echo "$as_me:$LINENO: result: $kde_cv_path" >&5
+-echo "${ECHO_T}$kde_cv_path" >&6
+-      ARTSCCONFIG=$kde_cv_path
+-
+-   fi
+-
+-
+    echo "$as_me:$LINENO: checking for kde-config" >&5
+ echo $ECHO_N "checking for kde-config... $ECHO_C" >&6
+    if test -n "$KDECONFIG"; then
+--- k3guitune/Makefile.am	2004-07-12 12:08:48.000000000 +0300
++++ k3guitune/Makefile.am	2005-06-30 20:30:54.000000000 +0300
+@@ -4,7 +4,7 @@
+ ## INCLUDES were found outside kdevelop specific part
  
-    echo "$as_me:$LINENO: checking for artsc-config" >&5
- echo $ECHO_N "checking for artsc-config... $ECHO_C" >&6
+ k3guitune_SOURCES = audiodlg.cpp soundinput.cpp k2guitune.cpp guitune.cpp osziview.cpp main.cpp logview.cpp k2guitune_meta_unload.cpp
+-k3guitune_LDADD = -lartsc -lkdeui -lkdecore $(LIBSOCKET)
++k3guitune_LDADD = -lkdeui -lkdecore $(LIBSOCKET)
+ 
+ 
+ EXTRA_DIST = k3guitune.desktop k2guitune_meta_unload.cpp logview.cpp logview.h main.cpp osziview.cpp osziview.h resources.h guitune.cpp guitune.h k2guitune.cpp k2guitune.h k3guituneui.rc soundinput.h soundinput.cpp audiodlg.h audiodlg.cpp 
+--- k3guitune/Makefile.in	2005-06-30 20:31:48.000000000 +0300
++++ k3guitune/Makefile.in	2005-06-30 20:31:03.000000000 +0300
+@@ -305,7 +305,7 @@
+ x_includes = @x_includes@
+ x_libraries = @x_libraries@
+ k3guitune_SOURCES = audiodlg.cpp soundinput.cpp k2guitune.cpp guitune.cpp osziview.cpp main.cpp logview.cpp k2guitune_meta_unload.cpp
+-k3guitune_LDADD = -lartsc -lkdeui -lkdecore $(LIBSOCKET)
++k3guitune_LDADD = -lkdeui -lkdecore $(LIBSOCKET)
+ EXTRA_DIST = k3guitune.desktop k2guitune_meta_unload.cpp logview.cpp logview.h main.cpp osziview.cpp osziview.h resources.h guitune.cpp guitune.h k2guitune.cpp k2guitune.h k3guituneui.rc soundinput.h soundinput.cpp audiodlg.h audiodlg.cpp 
+ 
+ ####### kdevelop will overwrite this part!!! (end)############
