adding lots of USE flags, checking kernel options, reworked init-scripts, added pcmcia support for kernels < 2.6.13 (new pcmcia support will follow soon), fixed pcap-0.9.3 issue (see bug 99190). Package-Manager: portage-2.0.51.22-r2

diff --git a/net-dialup/isdn4k-utils/files/hisax.initd b/net-dialup/isdn4k-utils/files/hisax.initd
--- a/net-dialup/isdn4k-utils/files/hisax.initd
+++ b/net-dialup/isdn4k-utils/files/hisax.initd
@@ -1,10 +1,24 @@
 #!/sbin/runscript
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-dialup/isdn4k-utils/files/hisax.initd,v 1.2 2005/07/01 22:34:02 sbriesen Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-dialup/isdn4k-utils/files/hisax.initd,v 1.3 2005/09/03 20:56:26 sbriesen Exp $
 
 depend() {
         use isapnp pcmcia
+}
+
+# possible firmware locations (list and order taken from 'capiinit')
+FWDIRS=(/lib/firmware/isdn /lib/firmware /usr/share/isdn /usr/lib/isdn /lib/isdn)
+
+# Firmware search
+findfw() {  # <fw_name>
+        local DIR
+        for DIR in ${FWDIRS[*]}; do
+                if [ -f "${DIR}/${1}" ]; then
+                        echo "${DIR}/${1}"; return 0
+                fi
+        done
+        return 1
 }
 
 check_module() {
@@ -17,8 +31,8 @@ get_first_free_idx() {
 	if ! read _it _lin < <(/bin/head 2>/dev/null -n1 /dev/isdninfo); then
 		echo "0"; return
 	fi
-	read -a _idxa < <(echo $_lin)
-	while [ $_idx -lt 65 ]; do
+	read -a _idxa < <(echo ${_lin})
+	while [ ${_idx} -lt 65 ]; do
 		: $((_idx++))
 		if [ "${_idxa[$_idx]}" = "-" ]; then
 			echo $((_idx / 2)); return
@@ -120,18 +134,18 @@ read_config() {
 	done < <(/bin/sed 2>/dev/null -ne "s:^[[:space:]]*\([1-9][0-9]\?[[:space:]]\+[^#]*\)[#]*.*$:\1:p" "$@")
 
 	# build final hisax options
-	if [ -n "$HISAX_TYPE" ]; then
+	if [ -n "${HISAX_TYPE}" ]; then
 		HISAX_OPTIONS="type=${HISAX_TYPE}"
-		[ "$HISAX_IRQ" = "$HISAX_DUMMY" ] || HISAX_OPTIONS="${HISAX_OPTIONS} irq=${HISAX_IRQ}"
-		[ "$HISAX_IO"  = "$HISAX_DUMMY" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io=${HISAX_IO}"
-		[ "$HISAX_IO0" = "$HISAX_DUMMY" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io0=${HISAX_IO0}"
-		[ "$HISAX_IO1" = "$HISAX_DUMMY" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io1=${HISAX_IO1}"
-		[ "$HISAX_MEM" = "$HISAX_DUMMY" ] || HISAX_OPTIONS="${HISAX_OPTIONS} mem=${HISAX_MEM}"
+		[ "${HISAX_IRQ}" = "${HISAX_DUMMY}" ] || HISAX_OPTIONS="${HISAX_OPTIONS} irq=${HISAX_IRQ}"
+		[ "${HISAX_IO}"  = "${HISAX_DUMMY}" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io=${HISAX_IO}"
+		[ "${HISAX_IO0}" = "${HISAX_DUMMY}" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io0=${HISAX_IO0}"
+		[ "${HISAX_IO1}" = "${HISAX_DUMMY}" ] || HISAX_OPTIONS="${HISAX_OPTIONS} io1=${HISAX_IO1}"
+		[ "${HISAX_MEM}" = "${HISAX_DUMMY}" ] || HISAX_OPTIONS="${HISAX_OPTIONS} mem=${HISAX_MEM}"
 		HISAX_OPTIONS="${HISAX_OPTIONS} protocol=${HISAX_PROTO} id=${HISAX_ID}"
 	fi
 
 	# build final hisax_fcpcipnp options
-	if [ -n "$HISAXFC_TYPE" ]; then
+	if [ -n "${HISAXFC_TYPE}" ]; then
 		HISAXFC_OPTIONS="protocol=${HISAXFC_PROTO}"
 	fi
 
@@ -139,7 +153,7 @@ read_config() {
 }
 
 start() {
-	if [ ! -e /etc/hisax.conf ]; then
+	if [ ! -f /etc/hisax.conf ]; then
 		eerror "You're missing /etc/hisax.conf"
 		return 1
 	fi
@@ -173,16 +187,22 @@ start() {
 	fi
 	eend $?
 
-	CNT=0  # wait for udev
-	while [ ! -e /dev/isdninfo -a $CNT -lt 10 ]; do
-		sleep 1; : $((CNT++))
-	done
+	# create ISDN devices if necessary
+	[ -c /dev/isdninfo -a -c /dev/isdnctrl0 ] || /etc/init.d/isdn makedev
 
 	if [ -n "${HISAX_FIRMWARE}" ]; then
 		for ID in ${HISAX_FIRMWARE}; do
-			ebegin "Loading firmware to ${ID}"
-			/usr/sbin/hisaxctrl ${ID} 9 /lib/firmware/ISAR.BIN
-			if ! eend $?; then
+			FW=$(findfw "ISAR.BIN")
+			if [ -n "${FW}" ]; then
+				ebegin "Loading firmware '${FW##*/}' onto ${ID}"
+				/usr/sbin/hisaxctrl "${ID}" 9 "${FW}"
+				if ! eend $?; then
+					/sbin/modprobe -sqr hisax_fcpcipnp
+					/sbin/modprobe -sqr hisax
+					return 1
+				fi
+			else
+				eerror "Firmware 'ISAR.BIN' not found in ${FWDIRS[0]}"
 				/sbin/modprobe -sqr hisax_fcpcipnp
 				/sbin/modprobe -sqr hisax
 				return 1
@@ -190,7 +210,7 @@ start() {
 		done
 	fi
 
-	CARDS=""
+	local CARDS="" ID VAL
 	if [ -n "${HISAX_DEBUG}" ]; then
 		for DBG in ${HISAX_DEBUG}; do
 			ID="${DBG%%\%*}"
@@ -199,7 +219,7 @@ start() {
 				ID="fcpcipnp${HISAX_CNT}"
 				: $((HISAX_CNT++))
 			fi
-			/usr/sbin/hisaxctrl ${ID} 1 ${VAL}
+			/usr/sbin/hisaxctrl "${ID}" 1 "${VAL}"
 			[ -z "${CARDS}" ] && CARDS="${ID}" || CARDS="${CARDS} ${ID}"
 		done
 	fi
@@ -212,4 +232,3 @@ stop() {
 	/sbin/modprobe -sqr hisax_fcpcipnp && /sbin/modprobe -sqr hisax
 	eend $?
 }
-
