Check configuration at service startup. Package-Manager: portage-2.1.1-r2

diff --git a/net-proxy/polipo/files/polipo.initd b/net-proxy/polipo/files/polipo.initd
--- a/net-proxy/polipo/files/polipo.initd
+++ b/net-proxy/polipo/files/polipo.initd
@@ -1,21 +1,49 @@
 #!/sbin/runscript
 # Copyright 1999-2005 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-proxy/polipo/files/polipo.initd,v 1.2 2006/09/06 20:29:15 mrness Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-proxy/polipo/files/polipo.initd,v 1.3 2007/02/12 11:13:22 mrness Exp $
 
 depend() {
 	need net
 }
 
+checkconfig() {
+	polipo -v | (
+    		local retvalue=0
+    		local name value desc
+		while read name value desc ; do
+			case ${name} in
+				configFile)
+					if [[ "${value}" == "(none)" ]]; then
+						eerror "Unable to read configuration file /etc/polipo/config"
+						retvalue=1
+					fi
+					;;
+				daemonise)
+					if [[ "${value}" != "false" ]]; then
+						eerror "Configuration option not supported by this init script: ${name}=${value}"
+						retvalue=1
+					fi
+					;;
+				pidFile)
+					if [[ "${value}" != "(none)" ]]; then
+						eerror "Configuration option not supported by this init script: ${name}=${value}"
+						retvalue=1
+					fi
+					;;
+			esac
+		done
+		return ${retvalue}
+	)
+	[[ ${PIPESTATUS[0]} == 0 && ${PIPESTATUS[1]} == 0 ]]
+	return $?
+}
+
 start() {
+	checkconfig || return 1
+
 	ebegin "Starting Polipo HTTP proxy"
-
-	if [ ! -f "/etc/polipo/config" ]; then
-		eerror "Unable to read configuration file: /etc/polipo/config"
-		return 1
-	fi
-
-	start-stop-daemon --start --quiet --chuid polipo \
+	start-stop-daemon --start --chuid polipo \
 		--background --pidfile /var/run/polipo.pid --make-pidfile \
 			--exec /usr/bin/polipo
 	eend $?
@@ -23,6 +51,6 @@ start() {
 
 stop() {
 	ebegin "Stopping Polipo HTTP proxy"
-	start-stop-daemon --stop --quiet --pidfile /var/run/polipo.pid
+	start-stop-daemon --stop --pidfile /var/run/polipo.pid
 	eend $?
 }
