New init script, with more thorough verification of the config, support for mounting the cgroup pseudo-fs, proper network dependencies, improved start-up (verifies that the container actually started up) and stop (won't waste time if the container was externally stopped). Package-Manager: portage-2.2_rc67/cvs/Linux x86_64

diff --git a/app-emulation/lxc/files/lxc.initd b/app-emulation/lxc/files/lxc.initd
--- a/app-emulation/lxc/files/lxc.initd
+++ b/app-emulation/lxc/files/lxc.initd
@@ -1,13 +1,17 @@
 #!/sbin/runscript
-# Copyright 1999-2010 Gentoo Foundation
+# Copyright 2010-2010 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/app-emulation/lxc/files/lxc.initd,v 1.1 2010/08/01 03:17:51 flameeyes Exp $
+# $Header: /var/cvsroot/gentoo-x86/app-emulation/lxc/files/lxc.initd,v 1.2 2010/08/01 21:13:46 flameeyes Exp $
 
 CONTAINER=${SVCNAME#*.}
 CONFIGFILE=${CONFIGFILE:-/etc/lxc/${CONTAINER}.conf}
 
-depend() {
-	 need net.lo localmount
+lxc_get_var() {
+    awk 'BEGIN { FS="[ \t]*=[ \t]*" } $1 == "'$1'" { print $2; exit }' ${CONFIGFILE}
+}
+
+cgroup_get_mount() {
+    mount | awk '$5 == "cgroup" { print $3; exit }'
 }
 
 checkconfig() {
@@ -16,37 +20,81 @@ checkconfig() {
 	eerror " ln -s lxc /etc/init.d/lxc.container"
 	return 1
     fi
+
+    utsname=$(lxc_get_var lxc.utsname)
+    if [ ${CONTAINER} != ${utsname} ]; then
+        eerror "You should use the same name for the service and the"
+        eerror "container. Right now the container is called ${utsname}"
+        return 1
+    fi
 }
 
-rootpath() {
-    sed -n -e 's:^[ \t]*lxc.rootfs[ \t]*=[ \t]*\(.*\)$:\1:p' ${CONFIGFILE}
+depend() {
+	# be quiet, since we have to run depend() also for the
+	# non-muxed init script, unfortunately.
+	checkconfig 2>/dev/null || return 0
+
+	config ${CONFIGFILE}
+	need localmount
+
+        # find out which network interface the container is linked to,
+        # and then require that to be enabled, so that the
+        # dependencies are correct.
+        netif=$(lxc_get_var lxc.network.link)
+        [ -n "${netif}" ] && need net.${netif}
 }
 
 start() {
     checkconfig || return 1
 
+    # make sure that cgroup is mounted if it isn't already, this
+    # ensures that we can actually proceed!
+    cgroupmount=$(cgroup_get_mount)
+    if [ -z ${cgroupmount} ]; then
+        mkdir -p /cgroup
+
+        if ! mount -t cgroup cgroup /cgroup; then
+            eerror "Unable to mount cgroup pseudo-filesystem on /cgroup"
+            return 1
+        fi
+
+        cgroupmount=/cgroup
+    fi
+
     rm /var/log/lxc/${CONTAINER}.log
+
+    rootpath=$(lxc_get_var lxc.rootfs)
 
     # Check the format of our init and the chroot's init, to see if we
     # have to use linux32 or linux64…
-    case $(scanelf -BF '%M#f' /sbin/init $(rootpath)/sbin/init | tr '\n' ':') in
+    case $(scanelf -BF '%M#f' /sbin/init ${rootpath}/sbin/init | tr '\n' ':') in
 	ELFCLASS64:ELFCLASS64:) setarch=;;
 	ELFCLASS32:ELFCLASS32:) setarch=;;
 	ELFCLASS32:ELFCLASS64:) setarch=linux64;;
 	ELFCLASS64:ELFCLASS32:) setarch=linux32;;
     esac
 
-    mkdir -p /var/log/lxc
-
     ebegin "Starting ${CONTAINER}"
     ${setarch} lxc-start -n ${CONTAINER} -f ${CONFIGFILE} -d -o /var/log/lxc/${CONTAINER}.log
+    sleep 0.5
+
+    # lxc-start -d will _always_ report a correct startup, even if it
+    # failed, so rather than trust that, check that the cgroup exists.
+    [ -d ${cgroupmount}/${CONTAINER} ]
     eend $?
 }
 
 stop() {
     checkconfig || return 1
 
-    local init_pid=$(head -n1 /cgroup/${CONTAINER}/tasks)
+    cgroupmount=$(cgroup_get_mount)
+
+    if ! [ -d ${cgroupmount}/${CONTAINER} ]; then
+        ewarn "${CONTAINER} doesn't seem to be started."
+        return 0
+    fi
+
+    init_pid=$(head -n1 ${cgroupmount}/${CONTAINER}/tasks)
 
     ebegin "Shutting down system in ${CONTAINER}"
     kill -INT ${init_pid}
@@ -64,4 +112,3 @@ stop() {
     lxc-stop -n ${CONTAINER}
     eend $?
 }
-
