Housekeeping Package-Manager: portage-2.0.51.22-r2

diff --git a/dev-db/phpmyadmin/files/reconfig b/dev-db/phpmyadmin/files/reconfig
--- a/dev-db/phpmyadmin/files/reconfig
+++ b/dev-db/phpmyadmin/files/reconfig
@@ -1,8 +1,16 @@
 #!/bin/bash
+
+die() {
+	echo "#####"
+	echo $1
+	echo "#####"
+	exit 1
+}
+
 if [ $1 = "install" ]; then
 	cd ${MY_INSTALLDIR}
-	sed -e "s|\$cfg\['PmaAbsoluteUri'\] = '';|\$cfg\['PmaAbsoluteUri'\] = 'http://${VHOST_HOSTNAME}${VHOST_APPDIR}';|g" -i config.inc.php
-		
+	sed -e "s|\$cfg\['PmaAbsoluteUri'\] = '';|\$cfg\['PmaAbsoluteUri'\] = 'http://${VHOST_HOSTNAME}${VHOST_APPDIR}';|g" -i config.inc.php || die "sed failed"
+
 elif [ $1 = "clean" ]; then
 	echo $1
 fi
