Fix reconfig script wrt bug #104495. Package-Manager: portage-2.0.51.22-r2

diff --git a/dev-db/phpmyadmin/files/reconfig b/dev-db/phpmyadmin/files/reconfig
--- a/dev-db/phpmyadmin/files/reconfig
+++ b/dev-db/phpmyadmin/files/reconfig
@@ -9,7 +9,7 @@ die() {
 
 if [ $1 = "install" ]; then
 	cd ${MY_INSTALLDIR}
-	sed -e "s|\$cfg\['PmaAbsoluteUri'\] = '';|\$cfg\['PmaAbsoluteUri'\] = 'http://${VHOST_HOSTNAME}${VHOST_APPDIR}';|g" -i config.inc.php || die "sed failed"
+	sed -e "s|\$cfg\['PmaAbsoluteUri'\] = '';|\$cfg\['PmaAbsoluteUri'\] = 'http://${VHOST_HOSTNAME}/${VHOST_APPDIR}';|g" -i config.inc.php || die "sed failed"
 
 elif [ $1 = "clean" ]; then
 	echo $1
