Remove old test version. Change init script for working with user-defined user/group (#108866). Add support for hashed User-Password under control of the frxp useflag (#109003) Package-Manager: portage-2.0.51.22-r3

diff --git a/net-dialup/freeradius/files/radius.init b/net-dialup/freeradius/files/radius.init
--- a/net-dialup/freeradius/files/radius.init
+++ b/net-dialup/freeradius/files/radius.init
@@ -18,21 +18,26 @@ checkconfig() {
 		return 1
 	fi
 
-	if [ -z "`grep radiusd /etc/passwd`" ] || [ -z "`grep radiusd /etc/group`" ]; then
-		eerror "radiusd user missing!"
+	RADIUSD_USER=`grep '^ *user *=' /etc/raddb/radiusd.conf | cut -d ' ' -f 3`
+	RADIUSD_GROUP=`grep '^ *group *=' /etc/raddb/radiusd.conf | cut -d ' ' -f 3`
+	if [ -n "${RADIUSD_USER}" ] && ! getent passwd ${RADIUSD_USER} > /dev/null ; then
+		eerror "${RADIUSD_USER} user missing!"
+		return 1
+	fi
+	if [ -n "${RADIUSD_GROUP}" ] && ! getent group ${RADIUSD_GROUP} > /dev/null ; then
+		eerror "${RADIUSD_GROUP} group missing!"
 		return 1
 	fi
 
-	if [ ! -f radius.log ]; then
-		touch radius.log && chown radiusd:radiusd radius.log \
-			|| return 1
-	fi
-	
-	return 0
+	#radius.log is created before privileges drop; we need to set proper permissions on it
+	[ -f radius.log ] || touch radius.log || return 1
+
+	chown -R "${RADIUSD_USER:-root}:${RADIUSD_GROUP:-root}" . && \
+		chmod -R u+rwX,g+rX . || return 1
 }
 
 start() {
-	cd /var/log/radius #set the location of log files
+	cd /var/log/radius #set the location of log files, including startup.log created by check-radiusd-config
 	# Comment out the following line to get faster startups
 	checkconfig || return 1
 
