Really fix init script --quiet reload, patch by Bernd Lommerzheim, bug #314055
Package-Manager: portage-2.2.0_alpha4/cvs/Linux x86_64

diff --git a/net-ftp/proftpd/files/proftpd.initd b/net-ftp/proftpd/files/proftpd.initd
--- a/net-ftp/proftpd/files/proftpd.initd
+++ b/net-ftp/proftpd/files/proftpd.initd
@@ -1,7 +1,7 @@
 #!/sbin/runscript
 # Copyright 1999-2010 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-ftp/proftpd/files/proftpd.initd,v 1.2 2010/07/29 21:50:32 voyageur Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-ftp/proftpd/files/proftpd.initd,v 1.3 2010/11/16 13:00:29 voyageur Exp $
 
 opts="reload"
 
@@ -16,13 +16,13 @@ check_configuration() {
 		eerror "file. In /etc/proftpd you can find a sample configuration."
 		return 1
 	fi
- 	/usr/sbin/proftpd -t &>/dev/null
- 	if [ $? -ne 0 ] ; then
- 		eerror "The ProFTPD configuration file /etc/proftpd/proftpd.conf is invalid! You have to"
- 		eerror "fix your configuration in order to run the ProFTPD server. For more information"
- 		eerror "you may execute the ProFTPD configuration check '/usr/sbin/proftpd -t'."
- 		return 2
- 	fi
+	/usr/sbin/proftpd -t &>/dev/null
+	if [ $? -ne 0 ] ; then
+		eerror "The ProFTPD configuration file /etc/proftpd/proftpd.conf is invalid! You have to"
+		eerror "fix your configuration in order to run the ProFTPD server. For more information"
+		eerror "you may execute the ProFTPD configuration check '/usr/sbin/proftpd -t'."
+		return 2
+	fi
 }
 
 start() {
@@ -44,12 +44,9 @@ stop() {
 }
 
 reload() {
-	if [ ! -f /var/run/proftpd/proftpd.pid ] ; then
-		eerror "ProFTPD is not running."
-		return 1
-	fi
 	check_configuration || return 1
 	ebegin "Reloading ProFTPD"
-	kill -HUP `cat /var/run/proftpd/proftpd.pid` &>/dev/null
+	start-stop-daemon --stop --quiet --signal HUP --oknodo \
+		--pidfile /var/run/proftpd/proftpd.pid
 	eend $?
 }
