Changing SHAREDIR to LOCAL_DIR in start scripts and einfo in ebuild (see bug #76278) Package-Manager: portage-1.589-cvs

diff --git a/net-p2p/gift/files/gift.initd b/net-p2p/gift/files/gift.initd
--- a/net-p2p/gift/files/gift.initd
+++ b/net-p2p/gift/files/gift.initd
@@ -1,7 +1,7 @@
 #!/sbin/runscript
 # Copyright 1999-2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-p2p/gift/files/gift.initd,v 1.5 2004/08/05 21:23:53 squinky86 Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-p2p/gift/files/gift.initd,v 1.6 2005/09/16 23:32:20 mkay Exp $
 
 depend() {
 	need net
@@ -10,13 +10,15 @@ depend() {
 start() {
 	ebegin "Starting giFTd"
 	start-stop-daemon --quiet --start -c ${USER} --make-pidfile \
-		--pidfile /var/run/giftd.pid --exec /usr/bin/giftd -- \
-		--local-dir=${SHAREDIR} &>${LOG} &
-	for i in `pgrep -u ${USER} giftd`
-	do
-		renice ${NICE} -p $i > /dev/null
-	done
-	eend $?
+		--pidfile /var/run/giftd.pid --exec /usr/bin/giftd \
+		--nicelevel ${NICE} -- \
+		--local-dir=${LOCAL_DIR} &>${LOG} &
+		result=$?
+	[ -z "`pgrep -u ${USER} giftd`" ] && result=1
+	if [ $result -eq 1 ]; then
+		eerror "Failed to start gift. Check ${LOG} for more information"
+	fi;
+	eend $result
 }
 
 stop() {
