syntax updates

diff --git a/sys-devel/perl/files/libperl_rebuilder b/sys-devel/perl/files/libperl_rebuilder
--- a/sys-devel/perl/files/libperl_rebuilder
+++ b/sys-devel/perl/files/libperl_rebuilder
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-LOG=/tmp/system-update.log
+LOG=/tmp/perl-update.log
+
+echo "The script will attempt to re-emerge your perl modules, any packages"
+echo "that compiled against libperl.so previously, as well as any packages"
+echo "that placed files in /usr/lib/perl*. A log of its attempts, work, and"
+echo "even failures is kept in ${LOG} - please refer to this log should you"
+echo "experience any difficulties."
+
 
 echo "--------------------------------------------------------------" >> $LOG
 echo "--------------------------------------------------------------" >> $LOG
@@ -41,23 +48,23 @@ echo 'Rechecking what perl modules you have installed...'
 echo 'Rechecking what perl modules you have installed...' >> $LOG
 
 
-MODULE_LIST=`
-	for i in $(ls -1| sort | uniq)
+SECOND_MODULE_LIST=`
+	for i in $(ls -1| sort -u)
 	do
 	   echo "dev-perl/${i}"
-	done | sort -u `
+	done | sed 's/-[0-9].*//g' | sort -u`
 
 
 
 x=0
 while [ $x -lt 3 ] ; do
 let "x++"
-for MODULE in $MODULE_LIST;
+for MODULE in $SECOND_MODULE_LIST;
   do
 	env-update
 	echo "Rebuilding: $MODULE, pass ${x}"
 	echo "Rebuilding: $MODULE, pass ${x}" >> $LOG
-	if ! emerge --oneshot "=$MODULE"; then
+	if ! emerge "$MODULE"; then
 		echo "emerge $MODULE FAILED while in rebuild, pass ${x}."
 		echo "emerge $MODULE FAILED while in rebuild, pass ${x}." >> $LOG
 	
@@ -73,6 +80,14 @@ done
 
 echo 'Preliminary Module Rebuild Complete. Now for rebuilding the rest...'
 echo 'Preliminary Module Rebuild Complete. Now for rebuilding the rest...' >> $LOG
+
+#This time around, we want the explicit package name, since in the group remerge, we use
+# a --oneshot =package syntax
+MODULE_LIST=`
+	for i in $(ls -1| sort -u)
+	do
+	   echo "dev-perl/${i}"
+	done | sort -u`
 
 
 echo 'Finding broken packages...'
@@ -93,12 +108,20 @@ done | sort -u`
 ORIGINAL_LIST="$LDD_LIST"
 
 if [ ! -z "$LDD_LIST" ]; then
-	REBUILD_LIST=`
+	REBUILD_PRELIST=`
 			echo $LDD_LIST | sed 's:\([^ ]\+\):=\1:g' | xargs emerge -p |
 			grep ebuild | sed 's:.*\] \([^ ]*\) .*:\1:'`
 fi
 
+# The following is to grab any packages that have placed files in
+# /usr/lib/perl* - this may include packages that are not explicityly
+# perl modules in dev-perl, or that did not compile against our old 
+# libperl - this is a sanity check among other things
 
+cd /var/db/pkg
+LIBS_LIST=`grep -ls "usr\/lib\/perl" */*/CONTENTS | sed 's|/CONTENTS||g'  | grep -v "sys-devel/perl" | grep -v "dev-perl"`
+
+REBUILD_LIST="echo ${LIBS_LIST} ${REBUILD_PRELIST} | sort -u"
 
 if echo $REBUILD_LIST | egrep -q "no.*ebuilds to satisfy"; then
   echo "Packages are installed that no longer exist in Gentoo."
@@ -107,6 +130,16 @@ if echo $REBUILD_LIST | egrep -q "no.*ebuilds to satisfy"; then
 	echo
 	echo "Easiest course of action: unmerge these by explicit versions"
 	echo "and re-emerge them if they still exist."
+	echo 'emerge -C \=package-version'
+	echo "Notice: $REBUILD_LIST"
+  exit 1
+fi
+
+if echo $REBUILD_LIST | grep -q "have been masked"; then
+  echo "Masked packages are installed and need to be rebuilt..."
+  echo "Either unmask them, or emerge -C them all."
+	echo
+	echo "Easiest course of action: unmerge these by explicit versions"
 	echo 'emerge -C \=package-version'
 	echo "Notice: $REBUILD_LIST"
   exit 1
@@ -151,31 +184,33 @@ if echo $REBUILD_LIST | grep -q "have been masked"; then
   echo "Masked packages are installed and need to be rebuilt..."
   echo "Either unmask them, or emerge -C them all."
 	echo
-	echo "Easiest course of action: unmerge these by explicit versions"
+	echo "Easiest course of action: check your ACCEPT_KEYWORDS in make.conf"
 	echo 'emerge -C \=package-version'
 	echo "Notice: $REBUILD_LIST"
   exit 1
 fi
 
-echo "Backing up the world file."
-cp /var/cache/edb/world /var/cache/edb/world.update_system_backup
-
-
-echo "Unmerging broken packages..."
-emerge -Cp $ORIGINAL_LIST | tee -a $LOG
-if ! emerge -C $ORIGINAL_LIST; then
-	echo
-	echo "There was a problem unmerging the broken packages."
-	echo "Please pass on your log file to a Gentoo Dev via bugzilla."
-	echo "Log file: $LOG"
-	echo
-	exit 1
-fi
-
-env-update
-
-echo "Restoring world file..."
-mv /var/cache/edb/world.update_system_backup /var/cache/edb/world
+# I'm commenting out the next block. I don't think that this is necessary for the
+# perl upgrade the same way it was for the gcc upgrade - MPC
+#echo "Backing up the world file."
+#cp /var/cache/edb/world /var/cache/edb/world.update_system_backup
+#
+#
+#echo "Unmerging broken packages..."
+#emerge -Cp $ORIGINAL_LIST | tee -a $LOG
+#if ! emerge -C $ORIGINAL_LIST; then
+#	echo
+#	echo "There was a problem unmerging the broken packages."
+#	echo "Please pass on your log file to a Gentoo Dev via bugzilla."
+#	echo "Log file: $LOG"
+#	echo
+#	exit 1
+#fi
+#
+#env-update
+#
+#echo "Restoring world file..."
+#mv /var/cache/edb/world.update_system_backup /var/cache/edb/world
 
 REBUILD_LIST=`
 	echo $LDD_LIST | sed 's:\([^ ]\+\):\\>\\=\1:g' | xargs emerge -np $(cat /var/cache/edb/world) |
@@ -197,7 +232,7 @@ if echo $REBUILD_LIST | grep -q "have been masked"; then
   echo "Masked packages are installed and need to be rebuilt..."
   echo "Either unmask them, or emerge -C them all."
 	echo
-	echo "Easiest course of action: unmerge these by explicit versions"
+	echo "Easiest course of action: check your ACCEPT_KEYWORDS in make.conf"
 	echo 'emerge -C \=package-version'
 	echo "Notice: $REBUILD_LIST"
   exit 1
