add shadow as DEPEND, fix distcc-config if shadow tools not installed

diff --git a/sys-devel/distcc/files/1.2.1/distcc-config b/sys-devel/distcc/files/1.2.1/distcc-config
--- a/sys-devel/distcc/files/1.2.1/distcc-config
+++ b/sys-devel/distcc/files/1.2.1/distcc-config
@@ -10,6 +10,7 @@
 # 
 # Additional features to come; this provides a starting point
 
+
 [ -z "${ROOT}" ] && ROOT=/
 
 source /sbin/functions.sh
@@ -20,6 +21,12 @@ DCCC_VERBOSE=1
 dccc_echo() {
 	[ -n "${DCCC_VERBOSE}" ] && echo "$*"
 }
+dccc_exit() {
+	dccc_echo "$*"
+	exit 1
+}
+
+[ "$(id -u)" != 0 ] && dccc_exit "$0 must be run by root"
 
 ###
 # the following functions manage the distcc symlinks
@@ -60,13 +67,27 @@ dccc_install_user() {
 	einfo "Updating or creating distcc user..."
 	local USERFIX
 	id distcc >/dev/null 2>&1 && USERFIX=usermod || USERFIX=useradd
-	${USERFIX} -g daemon -s /bin/false -d /dev/null \
-		-c "distccd" distcc || die
+	USERFIX="/usr/sbin/${USERFIX}"
+	if [ -x "${USERFIX}" ]
+	then
+		if ! ${USERFIX} -g daemon -s /bin/false -d /dev/null \
+				-c "distccd" distcc 
+		then
+			dccc_exit "unable to create or modify user"
+		fi
+	elif [ "${USERFIX}" = "/usr/sbin/useradd" ]
+	then
+		ewarn "${USERFIX} not found: You need to add the distcc user"
+		ewarn "to /etc/passwd by hand.  Add the following line:\n"
+		ewarn "  distcc:x:240:2:distccd:/dev/null:/bin/false\n"
+		ewarn "and then run 'distcc-config --install' again root."
+		dccc_exit "Unable to create distcc user!"
+	fi
 
 	for d in ${ROOT}usr/lib/distcc/bin ${ROOT}var/run/distccd ; do
 		einfo "Configuring $d..."
-		chown distcc:daemon $d
-		chmod 0755 $d
+		chown distcc:daemon $d && chmod 0755 $d || \
+			dccc_exit "Unable to configure ${d}!"
 	done
 }
 
