version bump and fix bug #31575. add metadata.xml

diff --git a/sys-apps/cpudyn/files/cpudyn.init b/sys-apps/cpudyn/files/cpudyn.init
--- a/sys-apps/cpudyn/files/cpudyn.init
+++ b/sys-apps/cpudyn/files/cpudyn.init
@@ -1,7 +1,12 @@
 #!/sbin/runscript
+# Copyright 1999-2003 Gentoo Technologies, Inc.
+# Distributed under the terms of the GNU General Public License v2
+# $Header: /var/cvsroot/gentoo-x86/sys-apps/cpudyn/files/cpudyn.init,v 1.2 2003/10/22 01:17:54 robbat2 Exp $
 #
 # Based on the Debian init script written by Celso Gonzalez <celso@bulma.net>,
 # and on the cpufreqd Gentoo init script written by Robert Gogolok <robertgogolok@web.de>.
+# Heavily modified by Robin H. Johnson <robbat2@gentoo.org> to ensure correct
+# start only under support conditions
 # 
 
 DAEMON=/usr/sbin/cpudynd
@@ -12,44 +17,44 @@ depend() {
 }
 
 checkconfig() {
-    local CPUFREQ_24="/proc/cpufreq"
-    local CPUFREQ_25="/sys/devices/system/cpu/cpu0/cpufreq /sysfs/devices/system/cpu/cpu0/cpufreq"
-    local CPUFREQ_ACPI="/proc/acpi/processor/CPU0/throttling"
-    local CPUFREQ_FILES="${CPUFREQ_24} ${CPUFREQ_25} ${CPUFREQ_ACPI}"
-    local CPUFREQ_FILE=""
-    for i in ${CPUFREQ_FILES}; do [ -e ${i} ] && CPUFREQ_FILE="${i}" && break ; done
-    if [ -z "${CPUFREQ_FILE}" ]; then
-        eerror "Neither CPUFreq nor ACPI throttling support were found"
+	local CPUFREQ_24="/proc/cpufreq"
+	local CPUFREQ_25="/sys/devices/system/cpu/cpu0/cpufreq /sysfs/devices/system/cpu/cpu0/cpufreq"
+	local CPUFREQ_ACPI="/proc/acpi/processor/CPU0/throttling"
+	local CPUFREQ_FILES="${CPUFREQ_24} ${CPUFREQ_25} ${CPUFREQ_ACPI}"
+	local CPUFREQ_FILE=""
+	for i in ${CPUFREQ_FILES}; do [ -e ${i} ] && CPUFREQ_FILE="${i}" && break ; done
+	if [ -z "${CPUFREQ_FILE}" ]; then
+		eerror "Neither CPUFreq nor ACPI throttling support were found"
 		return 1
-    fi
-    if [ "${CPUFREQ_FILE}" = "${CPUFREQ_ACPI}" ]; then
-        # see if the file says we are supported or not
-        grep 'not supported' ${CPUFREQ_ACPI} 2>&1 >/dev/null
-        retval="$?"
-        if [ $retval -eq 0 ]; then
-		    eerror "ACPI throttling support found, but hardware doesn't support it"
-		    return 1
-        fi
-        # now check that we can write to the file
-        local acpistate=`grep 'active state' ${CPUFREQ_ACPI} | cut -dT -f2-`
-        echo $acpistate > ${CPUFREQ_ACPI}
-        retval="$?"
-        if [ ! $retval -eq 0 ]; then
-		    eerror "Writing to ACPI throttling file failed"
-		    return 1
-        fi
-    fi
+	fi
+	if [ "${CPUFREQ_FILE}" = "${CPUFREQ_ACPI}" ]; then
+		# see if the file says we are supported or not
+		grep 'not supported' ${CPUFREQ_ACPI} 2>&1 >/dev/null
+		retval="$?"
+		if [ $retval -eq 0 ]; then
+			eerror "ACPI throttling support found, but hardware doesn't support it"
+			return 1
+		fi
+		# now check that we can write to the file
+		local acpistate=`grep 'active state' ${CPUFREQ_ACPI} | cut -dT -f2-`
+		echo $acpistate > ${CPUFREQ_ACPI}
+		retval="$?"
+		if [ $retval -ne 0 ]; then
+			eerror "Writing to ACPI throttling file failed"
+			return 1
+		fi
+	fi
 }
 
 
 start() {
-    local CPUDYN_OPTS="-d"
+	local CPUDYN_OPTS=""
 	if [ -n "$INTERVAL" ]; then CPUDYN_OPTS="$CPUDYN_OPTS -i $INTERVAL"; fi
 	if [ -n "$CPU_UP" -a -n "$CPU_DOWN" ]; then CPUDYN_OPTS="$CPUDYN_OPTS -p $CPU_UP $CPU_DOWN"; fi
 	if [ -n "$THROTTLING_LOW" ]; then CPUDYN_OPTS="$CPUDYN_OPTS -l $THROTTLING_LOW"; fi
 	if [ -n "$TIMEOUT" ]; then CPUDYN_OPTS="$CPUDYN_OPTS -t $TIMEOUT"; fi
 	if [ -n "$DISKS" ]; then CPUDYN_OPTS="$CPUDYN_OPTS -h $DISKS"; fi
-	
+
 	ebegin "Starting cpudynd"
 	if checkconfig; then
 		start-stop-daemon --start --quiet --pidfile $PIDFILE \
@@ -66,3 +71,5 @@ stop() {
 		--exec $DAEMON && rm -f $PIDFILE
 	eend $?
 }
+
+# vim:ts=4 noexpandtab:
