Revision bump for total rewrite of the init script.
Package-Manager: portage-2.2.0_alpha34/cvs/Linux x86_64

diff --git a/sci-misc/boinc/files/boinc.init b/sci-misc/boinc/files/boinc.init
--- a/sci-misc/boinc/files/boinc.init
+++ b/sci-misc/boinc/files/boinc.init
@@ -1,7 +1,6 @@
 #!/sbin/runscript
 
 opts="${opts} attach"
-PIDFILE=/var/run/boinc.pid
 
 depend() {
 	# we can use dns and net, but we can also in most cases live without them
@@ -12,21 +11,13 @@ create_work_directory() {
 	if [ ! -d "${RUNTIMEDIR}" ]; then
 		einfo "Directory ${RUNTIMEDIR} not existing, creating now."
 		mkdir "${RUNTIMEDIR}"
-		chown "${USER}:${GROUP}" "${RUNTIMEDIR}"
 		if [ ! -d "${RUNTIMEDIR}" ]; then
 			eeror "Directory ${RUNTIMEDIR} could not be created!"
 			return 1
 		fi
-		ln -s /etc/ssl/certs/ca-certificates.crt "${RUNTIMEDIR}"/ca-bundle.crt
 	fi
-}
-
-generate_logs() {
-	if [ ! -f "${LOGFILE}" ]; then
-		einfo "No ${LOGFILE} around. Creating new..."
-		einfo "You really should use app-admin/logrotate for the log rotation."
-		touch "${LOGFILE}"
-		chown "${USER}:${GROUP}" "${LOGFILE}"
+	if [ ! -e "${RUNTIMEDIR}"/ca-bundle.crt ] ; then
+		ln -s /etc/ssl/certs/ca-certificates.crt "${RUNTIMEDIR}"/ca-bundle.crt
 	fi
 }
 
@@ -37,16 +28,23 @@ cuda_check() {
 	fi
 }
 
-start() {
-	ebegin "Starting BOINC"
+check_baselayout() {
+	if [ "${RC_VERSION:-0}" = "0" ]; then
+		eerror "This script cannot be used for baselayout-1."
+		return 1
+	fi
+}
 
+start() {
+	check_baselayout || return 1
 	create_work_directory || return 1
 	cuda_check
 
-	cd "${RUNTIMEDIR}"
+	# always ensure proper ownership
+	chown -R "${USER}:${GROUP}" "${RUNTIMEDIR}"
 
-	if [ ! -f lockfile ]; then
-		einfo "File $RUNTIMEDIR/lockfile does not exist, assuming first run."
+	if [ ! -f "${RUNTIMEDIR}/lockfile" ]; then
+		einfo "File \"${RUNTIMEDIR}/lockfile\" does not exist, assuming first run."
 		einfo "You need to setup an account on the BOINC project homepage beforehand!"
 		einfo "Go to http://boinc.berkeley.edu/ and locate your project."
 		einfo "Then either run /etc/init.d/boinc attach or connect with a gui client"
@@ -60,65 +58,46 @@ start() {
 		ARGS="${ARGS} --allow_remote_gui_rpc"
 	fi
 
-	if [ -n "${RC_UNAME}" ]; then
-		PARAMS="--background --stdout '${LOGFILE}' --stderr '${LOGFILE}' -- ${ARGS}"
-	else
-		PARAMS="-- ${ARGS} >> '${LOGFILE}' 2>&1"
-	fi
-
-	generate_logs
-
-	start-stop-daemon \
-		--start --quiet --chdir "${RUNTIMEDIR}" \
-		--make-pidfile \
-		--pidfile "${PIDFILE}" \
-		--chuid "${USER}:${GROUP}" \
-		--nicelevel "${NICELEVEL}" \
-		--exec "${BOINCBIN}" ${PARAMS}
-
-	RESULT=$?
-
-	eend ${RESULT}
+	ebegin "Starting ${SVCNAME}"
+	su -m ${USER} -c "nice -n ${NICELEVEL} \"${BOINCBIN}\" ${ARGS} --daemon --dir \"${RUNTIMEDIR}\" --redirectio"
+	eend $?
 }
 
 attach() {
-	local password args url key
-	local was_started=true
+	local password url key
+
+	einfo "If you cant find your account key just try to obtain it by using:"
+	einfo "    boinccmd --passwd PASSWORD_FROM_GUI_RPC_AUTH --lookup_account URL EMAIL PASSWORD"
 
 	printf "    Enter the Project URL: "
 	read url
 	printf "    Enter your Account Key: "
 	read key
 
-	password=$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")
-	args="--project_attach ${url} ${key}"
-
 	if ! service_started; then
-		was_started=false
 		"${RC_SERVICE}" start
 	fi
 
-	ebegin "Attaching to project"
-		boinccmd --host localhost --passwd "${password}" ${args}
+	password=$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")
+
+	ebegin "${SVCNAME}: Attaching to project"
+	su -m ${USER} -c "boinccmd --passwd "${password}" --project_attach ${url} ${key}"
 	eend $?
 
-	unset password args url key
+	unset password url key
 
 	sleep 10
-	tail "${LOGFILE}"
-
-	[[ ${was_started} = "false" ]] && "${RC_SERVICE}" stop
+	tail "${RUNTIMEDIR}/stdoutdae.txt"
 }
 
 stop() {
-	ebegin "Stopping BOINC"
-	start-stop-daemon --stop --retry 3 --quiet --exec "${BOINCBIN}"
-	rm -f "${PIDFILE}"
-	eend $?
-}
+	local password
 
-restart() {
-	stop
-	sleep 3
-	start
+	password=$(cat "${RUNTIMEDIR}/gui_rpc_auth.cfg")
+
+	ebegin "Stopping ${SVCNAME}"
+	su -m ${USER} -c "boinccmd --passwd "${password}" --quit"
+	eend $?
+
+	unset password
 }
