Clean up old versions, several cleanups closing bug 103558, 109567 and 110606. Thanks to Tony Murrary <tonymurray@fastmail.fm> and Benjamin Gaillard <gentoo@powercode.net>. Package-Manager: portage-2.0.53_rc6

diff --git a/sci-misc/boinc/files/boinc.init b/sci-misc/boinc/files/boinc.init
--- a/sci-misc/boinc/files/boinc.init
+++ b/sci-misc/boinc/files/boinc.init
@@ -38,7 +38,8 @@ start() {
 	fi
 
 	setsid start-stop-daemon --quiet --start --exec ${BOINCBIN} \
-		--chuid ${USER}:${GROUP} --nicelevel ${NICELEVEL} -- ${ARGS} > ${LOGFILE} 2>&1 &
+		--chuid ${USER}:${GROUP} --nicelevel ${NICELEVEL} -- ${ARGS} \
+		--chdir ${RUNTIMEDIR} > ${LOGFILE} 2>&1 &
 
 	eend $?
 }
@@ -50,16 +51,15 @@ attach() {
 	read key
 
 	RC_QUIET_STDOUT="yes" svc_status
-	if [ $? == 0 ]; then
-		ebegin "Attaching to project"
-			# boinc cmd does not return 1 when it fails currently
-			boinc_cmd --project_attach ${url} ${key} &> /dev/null
-		eend $?
-	else
-		ARGS="${ARGS} -attach_project ${url} ${key}" svc_start
+	if [ $? == 1 ]; then
+		svc_start
 	fi
+	ebegin "Attaching to project"
+		# boinc cmd does not return 1 when it fails currently
+		boinc_cmd --project_attach ${url} ${key} &> /dev/null
+	eend $?
 
-	sleep 9
+	sleep 10
 	tail ${LOGFILE}
 }
 
