minor init script fix: if a daemon doesn't start, stop all companions

diff --git a/net-fs/samba/files/samba-init b/net-fs/samba/files/samba-init
--- a/net-fs/samba/files/samba-init
+++ b/net-fs/samba/files/samba-init
@@ -1,7 +1,7 @@
 #!/sbin/runscript
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License, v2 or later
-# $Header: /var/cvsroot/gentoo-x86/net-fs/samba/files/samba-init,v 1.5 2004/06/11 14:30:14 satya Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-fs/samba/files/samba-init,v 1.6 2004/06/12 14:45:13 satya Exp $
 
 opts="${opts} reload"
 
@@ -35,7 +35,12 @@ function signal_do {
 start() {
 	${my_service_PRE}
 	signal_do start
-	eend $?
+	result_start=$?
+	if [ ${result_start} -gt 0 ]; then
+		ewarn "Error: stopping services (see system logs)"
+		signal_do stop
+	fi
+	eend ${result_start}
 }
 stop() {
 	${my_service_PRE}
