Fixed typo in wrapper script Package-Manager: portage-2.1

diff --git a/mail-filter/popfile/files/popfile b/mail-filter/popfile/files/popfile
--- a/mail-filter/popfile/files/popfile
+++ b/mail-filter/popfile/files/popfile
@@ -25,7 +25,7 @@ if [[ ! -d $POPFILE_DIR ]] ; then
 fi
 
 if [[ ! -e $POPFILE_DIR/$POPFILE_PL ]] ; then
-	echo "*** error: popfile.pl is missing or not executable" > &2
+	echo "*** error: popfile.pl is missing or not executable" >&2
 	exit 1
 fi
 
