Fix bug 41074 by allowing multiple urls and url|url syntax

diff --git a/net-www/mozilla-firebird/files/MozillaFirebird b/net-www/mozilla-firebird/files/MozillaFirebird
--- a/net-www/mozilla-firebird/files/MozillaFirebird
+++ b/net-www/mozilla-firebird/files/MozillaFirebird
@@ -2,9 +2,10 @@
 #
 # Copyright 1999-2004 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License, v2 or later
-# $Header: /var/cvsroot/gentoo-x86/net-www/mozilla-firebird/files/MozillaFirebird,v 1.6 2004/02/07 19:49:34 agriffis Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-www/mozilla-firebird/files/MozillaFirebird,v 1.7 2004/02/12 20:31:15 agriffis Exp $
 
-# Set to "window" if you prefer new Firebird windows instead of new tabs
+# Set MOZILLA_NEWTYPE to "window" in your environment if you prefer
+# new Firebird windows instead of new tabs
 newtype=${MOZILLA_NEWTYPE:-"tab"}
 
 # Point this to your Firebird installation if not using the default
@@ -17,28 +18,22 @@ if [[ -z $DISPLAY ]]; then
   exit 1
 fi
 
-# Validate the args and extract the url
-url=''
-declare -a args=($@)
+# Validate the args and extract the urls
+args=()
+urls=()
 while [[ $# -ne 0 ]] ; do
   if [[ $1 == -* ]] ; then
-    case ${1#-} in
+    case "${1#-}" in
       height|width|CreateProfile|P|UILocale|contentLocale|remote|edit|chrome)
+        args=("${args[@]}" "$1" "$2")
         shift 2 ;;
       *)
+        args=("${args[@]}" "$1")
         shift 1 ;;
     esac
   else
-    if [[ -n $url ]] ; then
-      echo "Usage error: more than one URL given" >&2
-      exit 255
-    else
-      url=$1
-      shift 1
-      if [[ $url != *:* ]] ; then
-        url=http://$url
-      fi
-    fi
+    urls=("${urls[@]}" $1)
+    shift
   fi
 done
 
@@ -68,28 +63,61 @@ for s in $DISPLAY "${screens[@]}"; do
   fi
 done
 
-if [[ ${#candidates[@]} > 0 ]]; then
-  for s in "${candidates[@]}"; do 
-    DISPLAY=${s} ${fbpath}/mozilla-xremote-client "openURL($url, new-$newtype)" \
-    && exit 0
-  done
-  retval=$?
-else
-  # simulate mozilla-xremote-client's response when it can't find an instance
-  retval=2
-fi
+# Make sure we'll get at least an empty window/tab
+[[ ${#urls[@]} == 0 ]] && urls=('')
 
-if [[ $retval -eq 2 || $retval -eq 3 ]] ; then
+# Handle multiple URLs by looping over the xremote call
+for u in "${urls[@]}"; do
+
+  # prepend http:// if needed
+  [[ $u == ? && $u != *:* ]] && u=http://$u
+
+  # try mozila-xremote-client on each candidate screen
+  if [[ ${#candidates[@]} > 0 ]]; then
+    for s in "${candidates[@]}"; do 
+      DISPLAY=${s} \
+        ${fbpath}/mozilla-xremote-client "openURL($u, new-$newtype)" \
+        && break
+    done
+    retval=$?
+  else
+    # simulate mozilla-xremote-client's response when it can't find an instance
+    retval=2
+  fi
+
   # 2 = No running windows found, so start a new instance
   # 3 = Thunderbird is running, but doesn't handle openURL command
   #     (or it might be an unresponsive Firebird)
-  ${fbpath}/MozillaFirebird "${args[@]}" && exit 0
+  if [[ $retval -eq 2 || $retval -eq 3 ]] ; then
+
+    # Handle case of multiple URLs
+    if [[ ${#urls[@]} > 1 ]]; then
+      ${fbpath}/MozillaFirebird "${args[@]}" "$u" &
+      if [[ -x /usr/bin/xtoolwait ]]; then
+        xtoolwait sleep 10
+      else
+        sleep 10   # totally arbitrary! :-(
+      fi
+      candidates=$DISPLAY
+      continue
+    fi
+
+    # Handle case of single URL
+    ${fbpath}/MozillaFirebird "${args[@]}" "$u" &
+    break
+
+  elif [[ $retval -eq 1 ]]; then
+    echo "Unable to connect to X server" >&2
+  elif [[ $retval -ne 0 ]]; then
+    echo "Unknown error $retval from mozilla-xremote-client" >&2
+  fi
+
+done
+
+# Will only wait here if MozillaFirebird was started by this script
+if ! wait; then
   retval=$?
-  echo "MozillaFirebird exited with non-zero status ($retval)" >&2
-elif [[ $retval -eq 1 ]] ; then
-  echo "Unable to connect to X server" >&2
-else
-  echo "Unknown error $retval from mozilla-xremote-client" >&2
+  echo "MozillaFirebird exited with non-zero status ($?)" >&2
 fi
 
 exit $retval
