version bump, fixes to wrapper scripts, cleaned out old builds Package-Manager: portage-2.0.51.22-r2

diff --git a/games-rpg/planeshift/files/planeshift b/games-rpg/planeshift/files/planeshift
--- a/games-rpg/planeshift/files/planeshift
+++ b/games-rpg/planeshift/files/planeshift
@@ -1,6 +1,13 @@
 #!/bin/sh
 
-cd /opt/planeshift
+PLANESHIFT_DIR="/opt/planeshift"
+
+if [ ! -d "$PLANESHIFT_DIR" ]; then
+        echo "Your Planeshift directory is missing. You need to reinstall Planeshift!"
+        exit 1
+fi
+
+cd "$PLANESHIFT_DIR"
 
 export CRYSTAL="/opt/crystal/lib/crystalspace"
 export CEL="/opt/crystal/lib/cel"
