Interblock l2tpd with xl2tpd. Install only basic configuration files and change init script to check the existence of the l2tpd.conf file (#134029). Package-Manager: portage-2.0.54-r2

diff --git a/net-dialup/l2tpd/files/l2tpd-init b/net-dialup/l2tpd/files/l2tpd-init
--- a/net-dialup/l2tpd/files/l2tpd-init
+++ b/net-dialup/l2tpd/files/l2tpd-init
@@ -1,13 +1,25 @@
 #!/sbin/runscript
-# Copyright 1999-2004 Gentoo Foundation
+# Copyright 1999-2006 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/net-dialup/l2tpd/files/l2tpd-init,v 1.3 2004/08/14 13:40:17 swegener Exp $
+# $Header: /var/cvsroot/gentoo-x86/net-dialup/l2tpd/files/l2tpd-init,v 1.4 2006/05/30 21:13:21 mrness Exp $
 
 depend() {
 	need net
 }
 
+checkconfig() {
+	if [[ ! -f /etc/l2tpd/l2tpd.conf ]] ; then
+		eerror "Missing /etc/l2tpd/l2tpd.conf configuration file!"
+		eerror "Example configuration file could be found in doc directory."
+		return 1
+	fi
+
+	return 0
+}
+
 start() {
+	checkconfig || return 1
+
 	ebegin "Starting l2tpd"
 	start-stop-daemon --start --quiet --exec /usr/sbin/l2tpd
 	eend $?
