USE=ssl support in config generation.  log dir moved to /var/log/webmin.  init script updated.

diff --git a/app-admin/webmin/files/webmin-gentoo-init b/app-admin/webmin/files/webmin-gentoo-init
--- a/app-admin/webmin/files/webmin-gentoo-init
+++ b/app-admin/webmin/files/webmin-gentoo-init
@@ -1,20 +1,37 @@
 #!/sbin/runscript
 # Copyright 1999-2004 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/app-admin/webmin/files/webmin-gentoo-init,v 1.2 2004/02/13 19:10:36 vapier Exp $
+# $Header: /var/cvsroot/gentoo-x86/app-admin/webmin/files/webmin-gentoo-init,v 1.3 2004/04/23 00:56:48 eradicator Exp $
 
 depend() {
 	need net logger
 }
 
-start() {
-	ebegin "Starting webmin"
-	/etc/webmin/start
+checkconfig() {
+	if [ -f /etc/webmin/config ]; then
+		return 0;
+	else
+		eerror "Error starting webmin.  Have you run '/usr/libexec/webmin/setup.sh'?"
+		return 1;
+	fi
+}
+
+start() { # copied from /etc/webmin/start
+	checkconfig || return 1
+	ebegin "Starting Webmin"
+
+	LANG=
+	export LANG
+
+	unset PERLIO
+	export PERLIO
+	start-stop-daemon --start --pidfile /var/run/webmin.pid --make-pidfile --quiet \
+		--exec /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
 	eend $?
 }
 
 stop() {
-	ebegin "Stopping webmin"
-	/etc/webmin/stop
+	ebegin "Stopping Webmin"
+	start-stop-daemon --stop --pidfile /var/run/webmin.pid --quiet
 	eend $?
 }
