Version bump wrt bug #113447. Package-Manager: portage-2.0.51.22-r2

diff --git a/www-apps/otrs/files/reconfig-2 b/www-apps/otrs/files/reconfig-2
--- a/www-apps/otrs/files/reconfig-2
+++ b/www-apps/otrs/files/reconfig-2
@@ -11,7 +11,7 @@ die() {
 if [ $1 = "install" ]; then
 	# edit Apache configs
 	cd ${VHOST_ROOT}/${PF}/scripts
-	sed -e "s|/opt/otrs/var/httpd/htdocs/|${MY_INSTALLDIR}/|g" -i apache-httpd.include.conf apache2-httpd.include.conf || die "sed 1 failed"
+	sed -e "s|/opt/otrs/var/httpd/htdocs/|${MY_INSTALLDIR}/|g" -i apache-httpd.include.conf apache2-httpd.include.conf || die "sed failed"
 	
 	# set $HOME
 	grep -lR "/opt" * | xargs sed -i "s|/opt/otrs|${VHOST_ROOT}/${PF}|g" || die "sed failed"
@@ -25,7 +25,7 @@ if [ $1 = "install" ]; then
 elif [ $1 = "clean" ]; then
 	echo "Please examine the contents of the following directories"
 	echo "and delete anything that is no longer necessary"
-	echo 
+	echo
 	echo ${VHOST_ROOT}/${PF}
 	echo ${MY_INSTALLDIR}
 fi
